ci: gha i learned reviewdog (#300)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -116,7 +116,7 @@ jobs:
       checks: write
       issues: write
       pull-requests: write
-    timeout-minutes: 15 # Consider increasing timeout
+    timeout-minutes: 15
 
     steps:
       - uses: actions/checkout@v4
@@ -130,30 +130,60 @@ jobs:
           locked: false
 
       - name: Run ruff check
-        run: pixi run -e test ruff-check --output-format github | tee ruff-lint.log
-
-      - name: Run ruff format
+        id: ruff_check
+        continue-on-error: true
         run: |
-          pixi run -e test ruff-format --check | tee ruff-format.log
-          echo "::group::Formatted output"
-          cat ruff-format.log
-          echo "::endgroup::"
-
-      - name: Post lint results as PR comments
+          pixi run -e test ruff-check --output-format github 
+          echo "RUFF_EXIT=$?" >> $GITHUB_ENV
+          
+      - name: Post ruff lint suggestions
         uses: reviewdog/action-suggester@v1
         with:
           tool_name: ruff-lint
-          fail_on_error: true
+          fail_level: none
           filter_mode: added
-          suggestions_file: ruff-lint.log
 
-      - name: Post format results as PR comments
+      - name: Run ruff format
+        id: ruff_format
+        continue-on-error: true
+        run: |
+          pixi run -e test ruff-format --exit-non-zero-on-format
+          echo "RUFF_FORMAT_EXIT=$?" >> $GITHUB_ENV
+
+      - name: Post ruff format suggestions
         uses: reviewdog/action-suggester@v1
         with:
           tool_name: ruff-format
-          fail_on_error: true
-          filter_mode: added
-          suggestions_file: ruff-format.log
+          fail_level: none
+          filter_mode: diff_context
+
+      # - name: Post mypy suggestions
+      #   uses: reviewdog/action-suggester@v1
+      #   with:
+      #     tool_name: type-check
+      #     fail_on_error: false
+      #     filter_mode: added
+      #     suggestions_file: type-check.log
+
+      - name: Run mypy check
+        id: mypy
+        continue-on-error: true
+        run: |
+          pixi run -e test type-check | tee type-check.log
+          echo "MYPY_EXIT=$?" >> $GITHUB_ENV
+
+      - name: Fail job if any linter/type checker found issues
+        env:
+          RUFF_EXIT: ${{ env.RUFF_EXIT }}
+          RUFF_FORMAT_EXIT: ${{ env.RUFF_FORMAT_EXIT }}
+          MYPY_EXIT: ${{ env.MYPY_EXIT }}
+        run: |
+          if [[ "$RUFF_EXIT" != "0" ]] || [[ "$RUFF_FORMAT_EXIT" != "0" ]] || [[ "$MYPY_EXIT" != "0" ]]; then
+            echo "One or more tools found issues."
+            exit 1
+          else
+            echo "All checks passed."
+          fi
 
   ################################################################################################
   # Build-Docs: Build documentation using mkdocs
